//LOGIN ACTION TYPE
export const FETCH_ACCOUNT_REQUEST = "FETCH_ACCOUNT_REQUEST";
export const FETCH_ACCOUNT_SUCCESS = "FETCH_ACCOUNT_SUCCESS";
export const FETCH_ACCOUNT_FAILURE = "FETCH_ACCOUNT_FAILURE";
export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";
export const AUTHENTICATE_FAILURE = "AUTHENTICATE_FAILURE";

//AGENT ACTION TYPE

export const ADD_AGENT_REQUEST = "ADD_AGENT_REQUEST";
export const ADD_AGENT_SUCCESS = "ADD_AGENT_SUCCESS";
export const ADD_AGENT_FAILURE = "ADD_AGENT_FAILURE";
export const DELETE_AGENT_REQUEST = "DELETE_AGENT_FAILURE";
export const DELETE_AGENT_SUCCESS = "DELETE_AGENT_SUCCESS";
export const DELETE_AGENT_FAILURE = "DELETE_AGENT_FAILURE";
export const FETCH_AGENT_BY_ID_REQUEST = "FETCH_AGENT_BY_ID_REQUEST";
export const FETCH_AGENT_BY_ID_SUCCESS = "FETCH_AGENT_BY_ID_SUCCESS";
export const FETCH_AGENT_BY_ID_FAILURE = "FETCH_AGENT_BY_ID_FAILURE";
export const UPDATE_AGENT_REQUEST = " UPDATE_AGENT_REQUEST";
export const UPDATE_AGENT_SUCCESS = " UPDATE_AGENT_SUCCESS";
export const UPDATE_AGENT_FAILURE = " UPDATE_AGENT_REQUEST_FAILURE";
export const GET_AGENT_LIST_REQUEST = "GET_AGENT_LIST_REQUEST";
export const GET_AGENT_LIST_SUCCESS = "GET_AGENT_LIST_SUCCESS";
export const GET_AGENT_LIST_FAILURE = "GET_AGENT_LIST_FAILURE";
export const POST_AGENT_REQUEST = "POST_AGENT_REQUEST";
export const POST_AGENT_SUCCESS = "POST_AGENT_SUCCESS";
export const POST_AGENT_FAILURE = "POST_AGENT_FAILURE";

// ROLE ACTION TYPE

export const GET_ROLES_LIST_REQUEST = "GET_ROLES_LIST_REQUEST";
export const GET_ROLES_LIST_SUCCESS = "GET_ROLES_LIST_SUCCESS";
export const GET_ROLES_LIST_FAILURE = "GET_ROLES_LIST_FAILURE";
export const FETCH_ROLE_REQUEST = "FETCH_ROLE_REQUEST";
export const FETCH_ROLE_SUCCESS = "FETCH_ROLE_SUCCESS";
export const FETCH_ROLE_FAILURE = "FETCH_ROLE_FAILURE";
export const DELETE_ROLE_REQUEST = "DELETE_ROLE_REQUEST";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAILURE = "DELETE_ROLE_FAILURE";
export const GET_ROLE_BY_ID_REQUEST = "GET_ROLE_BY_ID_REQUEST";
export const GET_ROLE_BY_ID_SUCCESS = "GET_ROLE_BY_ID_SUCCESS";
export const GET_ROLE_BY_ID_FAILURE = "GET_ROLE_BY_ID_FAILURE";
export const POST_ROLE_REQUEST = "POST_ROLE_REQUEST";
export const POST_ROLE_SUCCESS = "POST_ROLE_SUCCESS";
export const POST_ROLE_FAILURE = "POST_ROLE_FAILURE";
export const GET_ROLE_REQUEST = "GET_ROLE_REQUEST";
export const GET_ROLE_SUCCESS = "GETT_ROLE_SUCCESS";
export const GET_ROLE_FAILURE = "GETT_ROLE_FAILURE";
export const UPDATE_ROLE_REQUEST = "UPDATE_ROLE_REQUEST";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAILURE = " UPDATE_ROLE_FAILURE";
export const FETCH_ROLE_BY_ID_FAILURE = "FETCH_ROLE_BY_ID_FAILURE ";
export const FETCH_ROLE_BY_ID_REQUEST = "FETCH_ROLE_BY_ID_REQUEST";
export const FETCH_ROLE_BY_ID_SUCCESS = " FETCH_ROLE_BY_ID_SUCCESS";

//ADMIN ACTION TYPE

export const GET_ADMIN_LIST_REQUEST = "GET_ADMIN_LIST_REQUEST";
export const GET_ADMIN_LIST_SUCCESS = "GET_ADMIN_LIST_SUCCESS";
export const GET_ADMIN_LIST_FAILURE = "GET_ADMIN_LIST_FAILURE";
export const POST_ADMIN_REQUEST = "POST_ADMIN_REQUEST";
export const POST_ADMIN_SUCCESS = "POST_ADMIN_SUCCESS";
export const POST_ADMIN_FAILURE = "POST_ADMIN_FAILURE";
export const FETCH_ADMIN_BY_ID_FAILURE = "FETCH_ADMIN_BY_ID_FAILURE";
export const FETCH_ADMIN_BY_ID_REQUEST = "FETCH_ADMIN_BY_ID_REQUEST";
export const FETCH_ADMIN_BY_ID_SUCCESS = "FETCH_ADMIN_BY_ID_SUCCESS";
export const DELETE_ADMIN_FAILURE = "DELTE_ADMIN_FAILURE";
export const DELETE_ADMIN_REQUEST = "DELETE_ADMIN_REQUEST";
export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";
export const UPDATE_ADMIN_REQUEST = "UPDATE_ADMIN_REQUEST";
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";
export const UPDATE_ADMIN_FAILURE = "UPDATE_ADMIN_FAILURE";

//CORPORATE ACTION TYPE

export const POST_CORPORATE_REQUEST = "POST_CORPORATE_REQUEST";
export const POST_CORPORATE_SUCCESS = "POST_CORPORATE_SUCCESS ";
export const POST_CORPORATE_FAILURE = "POST_CORPORATE_FAILURE";
export const DELETE_CORPORATE_SUCCESS = "DELETE_CORPORATE_SUCCESS";
export const DELETE_CORPORATE_REQUEST = "DELETE_CORPORATE_FAILURE";
export const DELETE_CORPORATE_FAILURE = "DELETE_CORPORATE_FAILURE";
export const FETCH_CORPORATE_BY_ID_REQUEST = "FETCH_CORPORATE_BY_ID_REQUEST";
export const FETCH_CORPORATE_BY_ID_SUCCESS = "FETCH_CORPORATE_BY_ID_SUCCESS";
export const FETCH_CORPORATE_BY_ID_FAILURE = "FETCH_CORPORATE_BY_ID_FAILURE";
export const UPDATE_CORPORATE_REQUEST = "UPDATE_CORPORATE_REQUEST";
export const UPDATE_CORPORATE_SUCCESS = "UPDATE_CORPORATE_SUCCESS";
export const UPDATE_CORPORATE_FAILURE = " UPDATE_CORPORATE_FAILURE";
export const GET_CORPORATE_REQUEST = "GET_CORPORATE_REQUEST";
export const GET_CORPORATE_SUCCESS = "GET_CORPORATE_SUCCESS";
export const GET_CORPORATE_FAILURE = "GET_CORPORATE_FAILURE";

// CLIENT ACTION TYPE

export const FETCH_CLIENT_BY_ID_REQUEST = "FETCH_CLIENT_BY_ID_REQUEST";
export const FETCH_CLIENT_BY_ID_SUCCESS = "FETCH_CLIENT_BY_ID_SUCCESS";
export const FETCH_CLIENT_BY_ID_FAILURE = "FETCH_CLIENT_BY_ID_FAILURE";
export const FETCH_CLIENT_BY_CIN_REQUEST = "FETCH_CLIENT_BY_CIN_REQUEST";
export const FETCH_CLIENT_BY_CIN_SUCCESS = "FETCH_CLIENT_BY_CIN_SUCCESS";
export const FETCH_CLIENT_BY_CIN_FAILURE = "FETCH_CLIENT_BY_CIN_FAILURE";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_REQUEST = "DELETE_CLIENT_FAILURE";
export const DELETE_CLIENT_FAILURE = "DELETE_CLIENT_FAILURE";
export const POST_CLIENT_REQUEST = "POST_CLIENT_REQUEST";
export const POST_CLIENT_SUCCESS = "POST_CLIENT_SUCCESS";
export const POST_CLIENT_FAILURE = "POST_CLIENT_FAILURE";
export const GET_CLIENT_CREDIT_SCORE_REQUEST =
  "GET_CLIENT_CREDIT_SCORE_REQUEST";
export const GET_CLIENT_CREDIT_SCORE_SUCCESS =
  "GET_CLIENT_CREDIT_SCORE_SUCCESS";
export const GET_CLIENT_CREDIT_SCORE_FAILURE =
  "GET_CLIENT_CREDIT_SCORE_FAILURE";
export const SET_SELECTED_CLIENT_SUCCESS = "SET_SELECTED_CLIENT_SUCCESS";
export const SET_SELECTED_CLIENT_REQUEST = "SET_SELECTED_CLIENT_REQUEST";
export const SET_SELECTED_CLIENT_FAILURE = "SET_SELECTED_CLIENT_FAILURE";
export const UPDATE_CLIENT_REQUEST = " UPDATE_CLIENT_REQUEST";
export const UPDATE_CLIENT_SUCCESS = " UPDATE_CLIENT_SUCCESS";
export const UPDATE_CLIENT_FAILURE = " UPDATE_CLIENT_FAILURE";

//ADDRESS ACTION TYPE
export const POST_ADDRESS_REQUEST = "POST_ADDRESS_REQUEST";
export const POST_ADDRESS_REQUEST_SUCCESS = "POST_ADDRESS_REQUEST_SUCCESS";
export const POST_ADDRESS_REQUEST_FAILURE = "POST_ADDRESS_REQUEST_FAILURE";
export const GET_ADDRESS_REQUEST = " GET_ADDRESS_REQUEST ";
export const GET_ADDRESS_SUCCESS = " GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_FAILURE = " GET_ADDRESS_FAILURE";
export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAILURE = "DELETE_ADDRESS_FAILURE";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAILURE = "UPDATE_ADDRESS_FAILURE";
export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";

// SCORE CONFIG ACTION TYPE

export const SAVE_SCORE_CONFIG_REQUEST = "SAVE_SCORE_CONFIG_REQUEST";
export const SAVE_SCORE_CONFIG_SUCCESS = "SAVE_SCORE_CONFIG_SUCCESS";
export const SAVE_SCORE_CONFIG_FAILURE = "SAVE_SCORE_CONFIG_FAILURE";

export const GET_SCORE_CONFIG_FAILURE = "GET_SCORE_CONFIG_FAILURE";
export const GET_SCORE_CONFIG_REQUEST = "GET_SCORE_CONFIG_REQUEST";
export const GET_SCORE_CONFIG_SUCCESS = "GET_SCORE_CONFIG_SUCCESS";
